version: '3'

services:
  emqx1:
    image: emqx/emqx-enterprise:latest
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.local"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local,emqx@node2.emqx.local]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - emqx1_data:/opt/emqx/data

  emqx2:
    image: emqx/emqx-enterprise:5.8.4
    container_name: emqx2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.emqx.local"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local,emqx@node2.emqx.local]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.local
    volumes:
      - emqx2_data:/opt/emqx/data

networks:
  emqx-bridge:
    driver: bridge

volumes:
  emqx1_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/emqx_n1
      o: bind
  emqx2_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/emqx_n2
      o: bind