version: '3.8'

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - ${PUBLIC_PORT}:80  # Change 8080 to any preferred port
    volumes:
      - nextcloud_html:/var/www/html
      - nextcloud_custom_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      SMTP_HOST: ${SMTP_HOST}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTHTYPE: ${SMTP_AUTHTYPE}
      SMTP_NAME: ${SMTP_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      REDIS_HOST_USER: ${REDIS_HOST_USER}
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      OBJECTSTORE_S3_BUCKET: ${OBJECTSTORE_S3_BUCKET}
      OBJECTSTORE_S3_REGION: ${OBJECTSTORE_S3_REGION}
      OBJECTSTORE_S3_HOST: ${OBJECTSTORE_S3_HOST}
      OBJECTSTORE_S3_PORT: ${OBJECTSTORE_S3_PORT}
      OBJECTSTORE_S3_KEY: ${OBJECTSTORE_S3_KEY}
      OBJECTSTORE_S3_SECRET: ${OBJECTSTORE_S3_SECRET}

volumes:
  nextcloud_html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_BASE_PATH}/nextcloud/html
  nextcloud_custom_apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_BASE_PATH}/nextcloud/custom_apps
  nextcloud_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUMES_BASE_PATH}/nextcloud/config
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}