version: '3.8'

services:

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
  
  goaccess:
    image: allinurl/goaccess
    ports:
      - 7890:7890
    volumes:
      - ${VOLUMES_BASE_PATH}/nginxproxymanager/configs/goaccess.vanilla.conf:/srv/config/goaccess.conf
      - ${VOLUMES_BASE_PATH}/nginxproxymanager/data/logs:/srv/logs
      - public:/srv/report
    command: ["--no-global-config", "--config-file=/srv/config/goaccess.conf"]
    restart: unless-stopped

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/nginxproxymanager/data
      o: bind
  
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/nginxproxymanager/letsencrypt
      o: bind
  
  public:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/nginxproxymanager/public
      o: bind