services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.2.1
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: ${POSTGRES_HOST}
      DB_SERVER_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEBUG_MODE: "true"
      PGPASSWORD: ${POSTGRES_PASSWORD}

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.2.1
    restart: unless-stopped
    container_name: zabbix-frontend
    ports:
      - "10052:8080"
      - "10053:8443"
    environment:
      DB_SERVER_HOST: ${POSTGRES_HOST}
      DB_SERVER_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DEBUG_MODE: "true"
      PGPASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - zabbix-server
