version: "3.8"

services:
  semaphore:
    image: semaphoreui/semaphore:v2.10.43
    restart: always
    ports:
      - 9010:3000
    environment:
      SEMAPHORE_DB_DIALECT: ${SEMAPHORE_DB_DIALECT}
      SEMAPHORE_DB_HOST: ${SEMAPHORE_DB_HOST}
      SEMAPHORE_DB_NAME: ${SEMAPHORE_DB_NAME}
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore

volumes:
  semaphore_data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/semaphore/data
      o: bind
  semaphore_config:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/semaphore/config
      o: bind
  semaphore_tmp:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_BASE_PATH}/semaphore/tmp
      o: bind